# ********************************************************************************************************* #
#                                                                                                           #
#                                                               :::::::::::    :::     :::    :::   :::     #
#    config.yml                                                 :+:        :+:     :+:    :+:   :+:         #
#                                                              +:+        +:+     +:+     +:+ +:+           #
#    By: Ivy <contact@1sheol.xyz>                             +#+        +#+     +:+      +#++:             #
#                                                            +#+         +#+   +#+        +#+               #
#    Created: 2024/11/04 00:52:13 by Ivy                    #+#         #+#+#+#         #+#                 #
#    Updated: 2024/11/04 00:52:13 by Ivy              ###########        ###           ###                  #
#                                                                                                           #
# ********************************************************************************************************* #



# This is the configuration file for the Brawl Stars Discord Rich Presence bot.
discord:
  clientId: "YOUR_DISCORD_CLIENT_ID" # Replace with your actual Discord client ID
  buttons:
    - label: "Button 1"
      url: "https://example.com/button1"
    - label: "Button 2"
      url: "https://example.com/button2"

api:
  playerUrl: "https://api.brawlstars.com/v1/players/PLAYER_ID" # Replace with your actual PlayerID 
  avatarUrl: "https://api.brawlify.com/v1/icons" # Replace with your actual avatar API URL

presence:
  details: "Your Presence Details"
  stateTemplate: "{trophies}🏆 | {name}"
  largeImageTextTemplate: "{name}"
  smallImageKey: "https://example.com/path/to/small/image.png"
  smallImageTextTemplate: "Club : {clubName}"
  updateInterval: 60 # in seconds



